operating_system: Ubuntu
domain: https://gacon1.gacontamnang.com/
topic: vietanh_oanhyen
collection_name: gacon
folders:
  work_folder: /home/gacontamnang/photobooth/
  root_folder: ./data
  save_folder: $topic_folder/images/
  processed_folder: $topic_folder/processed/
  frame_folder: $topic_folder/frames/
printer:
  name: Canon SELPHY CP1000
  code: CP1000
camera:
  name: Nikon D3300
  code: d3300
  streaming_camera_id: 1
commands:
  printer:
    control_printer_command:
    - lp
    - -d
    - $printer_code
    - -o
    - PageSize=Postcard
    - -o
    - StpBorderless=True
    - -o
    - StpiShrinkOutput=None
    - -o
    - orientation-requested=4
    - -o
    - scaling=100
    - -o
    - natural-scaling=100
    - -o
    - fit-to-page=False
    - -o
    - StpBorderlessExpand=False
    - -o
    - StpScale=False
    - -n
    - 1
    - $image_path
    stat_printer_command:
    - lpstat
    - -p
  camera:
    control_cam_command:
    - gphoto2
    - --capture-image-and-download
    - --filename
    - $image_path
    - --force-overwrite
    stat_cam_command:
    - gphoto2
    - --auto-detect
  system:
    reboot_command:
    - sudo
    - reboot
    list_wifi_command:
    - nmcli
    - -t
    - -f
    - SSID,SIGNAL,SECURITY
    - device
    - wifi
    - list
    connect_wifi_command:
    - sudo
    - nmcli
    - device
    - wifi
    - connect
    - $wifi_ssid
    - password
    - $wifi_password
    - ifname
    - $wifi_iface
wifi:
  ssid: VNPT_Doi_5G
  password: 0966236112
