operating_system: Windows
domain: https://gacon1.gacontamnang.com/
topic: levinh_kimanh
collection_name: gacon
folders:
  root_folder: ./data
  save_folder: $topic_folder/images/
  processed_folder: $topic_folder/processed/
  frame_folder: $topic_folder/frames/
printer:
  name: Canon SELPHY CP1000
  code: CP1000
camera:
  name: Nikon D3300
  code: D3300
  streaming_camera_id: 1
commands:
  printer:
    control_printer_command:
    - rundll32
    - shimgvw.dll,ImageView_PrintTo
    - /pt
    - $image_path
    - $printer_code
    stat_printer_command:
    - lpstat
    - -p
  camera:
    control_cam_command:
    - gphoto2
    - --capture-image-and-download
    - --filename
    - $image_path
    - --force-overwrite
    stat_cam_command:
    - gphoto2 
    - --auto-detect
